// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	CustomerID uuid.UUID   `json:"customer_id"`
	FirstName  pgtype.Text `json:"first_name"`
	LastName   pgtype.Text `json:"last_name"`
	Email      pgtype.Text `json:"email"`
	Phone      pgtype.Text `json:"phone"`
	Address    pgtype.Text `json:"address"`
}

type Product struct {
	ProductID uuid.UUID      `json:"product_id"`
	Name      pgtype.Text    `json:"name"`
	Price     pgtype.Numeric `json:"price"`
	VendorID  uuid.UUID      `json:"vendor_id"`
}

type Service struct {
	ServiceID uuid.UUID        `json:"service_id"`
	Name      pgtype.Text      `json:"name"`
	Price     pgtype.Numeric   `json:"price"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}

type Vendor struct {
	VendorID uuid.UUID   `json:"vendor_id"`
	Name     string      `json:"name"`
	Contact  pgtype.Text `json:"contact"`
	Phone    pgtype.Text `json:"phone"`
	Email    pgtype.Text `json:"email"`
	Address  pgtype.Text `json:"address"`
}
