// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeleteCustomer(ctx context.Context, customerID uuid.UUID) error
	GetCustomer(ctx context.Context, customerID uuid.UUID) (Customer, error)
	GetCustomerForUpdate(ctx context.Context, customerID uuid.UUID) (Customer, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	UpdateCustomerEmail(ctx context.Context, arg UpdateCustomerEmailParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
